// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uogtqbqohohremldbhmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZ3RxYnFvaG9ocmVtbGRiaG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODY1OTAsImV4cCI6MjA2MDY2MjU5MH0.3ok11CGtHdk5qBAklbiWLGGBJW28q7aggWcAZQXPGzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);